### ISSUE TITLE
apple login not working

### ISSUE THREAD

**Issue by maxbhoria** [aboutyou/dart_packages#156] opened 2020-10-05 19:57 UTC
Hello, 
apple login is not working using face id. Please help me in this.

Thanks in advance

**Comment by HenriBeck** [comment] 2020-10-06 06:23
@maxbhoria please provide the following information:

- `flutter doctor -v` output
- Version of `sign_in_with_apple`
- XCode logs when attempting the sign in

**Comment by maxbhoria** [comment] 2020-10-07 18:00
I can't share you face id apple login logs because thats happening in client device.

sign_in_with_apple version= sign_in_with_apple: ^2.5.2

Flutter doctor

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E287, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.47.2)
[!] Connected device
    ! No devices available

**Comment by HenriBeck** [comment] 2020-10-07 20:38
Yes you can, you just have to connect your iPhone to your Mac and then run your debug build on the real iPhone through XCode.

**Comment by maxbhoria** [comment] 2020-10-08 09:19
I have shared an ipa file to client so i and the client reported me that its not working.

**Comment by HenriBeck** [comment] 2020-10-09 12:48
Without logs, we can't help you.

**Comment by maxbhoria** [comment] 2020-10-11 04:55
This happening when i shared build to client so can you check at your end why this happening in release build?

**Comment by HenriBeck** [comment] 2020-10-11 08:51
@maxbhoria, this is working in our own app, so the issue is most likely not on our side. Please provide XCode logs, which should mention the correct reason why this isn't working. Until then, we can't help you.

**Comment by maxbhoria** [comment] 2020-10-11 15:14
yes its working in side as well but only in simulator not in ios real device dont why?

**Comment by HenriBeck** [comment] 2020-10-12 19:43
@maxbhoria I can't tell you why it's not working without seeing any XCode logs from a real device.

This is working fine for our own app and other ones, so I think it's a configuration issue on your side. Please make sure you followed our [readme](https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple) correctly.

**Comment by HenriBeck** [comment] 2020-10-19 21:17
Closing this until more information (XCode logs) are provided

**Closed by HenriBeck** 2020-10-19 21:17 UTC
