### ISSUE TITLE
[sign_in_with_apple] Apple Sign in not working on real device ios 13.6

### ISSUE THREAD

**Issue by chubzchoc** [aboutyou/dart_packages#118] opened 2020-07-27 08:42 UTC
I have issue on version 2.5.2.
I can login using apple on simulator. But it doesn't work on my real phone. 
this plugin can work correctly on previous ios version 13.5.1 (both on real phone and simulator).

**Comment by HenriBeck** [comment] 2020-07-27 08:45
@chubzchoc, could you please provide more detail about error messages? With version 2.5.2, we didn't change anything regarding iOS, so it shouldn't be affected.

**Comment by HenriBeck** [comment] 2020-07-27 08:48
I will update my phone to iOS 13.6 and check if it's also broken on our app

**Comment by chubzchoc** [comment] 2020-07-27 08:52
Ok . thank you. 
Please help to check it.

**Comment by HenriBeck** [comment] 2020-07-27 08:53
@chubzchoc do you have any error logs?

**Comment by chubzchoc** [comment] 2020-07-27 09:01
sorry i don't have it.

**Comment by HenriBeck** [comment] 2020-07-27 09:10
@chubzchoc for me it worked on iOS 13.6, so you will need to provide some error logs before we can look at this issue again

**Comment by shinriyo** [comment] 2020-08-04 03:31
I can't too
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: SignInWithAppleNotSupportedException(Unsupported platform version: iOS 12.4.1)
```

**Comment by HenriBeck** [comment] 2020-08-04 12:47
@shinriyo you are clearly trying it on iOS 12.4 where Sign in with Apple is not supported.

**Comment by shinriyo** [comment] 2020-08-04 13:42
@HenriBeck iOS 12.4 doesn't support?
So, how to log in with Apple login?


I just check with it.
```
                final isAvailable = await SignInWithApple.isAvailable();
                if (isAvailable) {
                  return;
                }
```

**Comment by romatallinn** [comment] 2020-08-04 22:04
@shinriyo "Sign in with Apple" feature was introduced only in iOS 13. While other popular OAuth interfaces (fb, google, etc) usually allow authentication via browser, Apple ID is integrated directly into OS itself.

**Comment by tp** [comment] 2020-08-05 11:49
@shinriyo If you really need to support iOS 12 (and some below), you can use the community fork from https://github.com/aboutyou/dart_packages/issues/99, which uses the web login on older iOS versions.

**Comment by HenriBeck** [comment] 2020-08-10 06:56
I'm closing this ticket as we haven't from @chubzchoc for more logs and haven't received other reports about issues with iOS 13.6

**Closed by HenriBeck** 2020-08-10 06:56 UTC
Labels: package:sign_in_with_apple

**Comment by chubzchoc** [comment] 2020-08-12 03:21
Now, when i run my app on simulator, it also error.
I got different error between real device and simulator. 

this is the error from real device : 
```
Aug 12 08:38:29 iPhone akd[135] <Notice>: Authorization ended for requestContext: <private>
Aug 12 08:38:29 iPhone XXXXX(AuthKit)[343] <Notice>: Authorization completed with authorization: <private>
Aug 12 08:38:29 iPhone XXXXX(Flutter)[343] <Notice>: flutter: ===
Aug 12 08:38:29 iPhone XXXXX(Flutter)[343] <Notice>: flutter: AuthorizationAppleID(001406.650604815b5f495aae1c89ce8bf47f55.0338, null, null, null, authorizationCode set? true, null)
Aug 12 08:38:29 iPhone XXXXX(Flutter)[343] <Notice>: flutter: ===
Aug 12 08:38:29 iPhone SpringBoard(SpringBoard)[55] <Notice>: <SBTransientOverlayPresentationManager: 0x28362e640>: Status bar owning view controller set to: <SBRemoteTransientOverlayViewController: 0x1264de600; contentViewController: <SBRemoteTransientOverlayHostViewController: 0x126b66a00; serviceBundleIdentifier: com.apple.AuthKitUIService; servicePID: 350>>
```


and this is the error from simulator
```
2020-08-12 10:16:09.156069+0700 XXXXX[17136:322327] [core] Authorization failed: Error Domain=AKAuthenticationError Code=-7034 "(null)" UserInfo={AKClientBundleID=com.xxxxx}
2020-08-12 10:16:09.184230+0700 XXXXX[17136:318932] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.))
#0      SignInWithApple.getAppleIDCredential (package:sign_in_with_apple/src/sign_in_with_apple.dart:137:7)
<asynchronous suspension>
#1      AccountController.apple_login (package:xxxxx/controller/AccountController.dart:337:46)
#2      _LoginState.build.<anonymous closure>.<anonymous closure> (package:xxxxx/view/login.dart:360:57)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
#7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#10     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#11     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#12     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#13     _rootRunUnary (dart:async/zone.dart:1206:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#16     _invoke1 (dart:ui/hooks.dart:267:10)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)

```

**Comment by tp** [comment] 2020-08-12 07:12
@chubzchoc Are you on Xcode 11.6? That seems to be a known regression on the Simulator sadly: https://developer.apple.com/forums/thread/656932

The real device logs look fine to me though (it logs that you received the credential). What's the issue there?

**Comment by chubzchoc** [comment] 2020-08-12 09:38
yes, I'm using xcode 11.6.

i just found the cause. 
i need the email and name credentials (email is required for the next process on my code). 
but the response give null value.

can i make email credentials required  or force user to share his/her email ?

**Comment by HenriBeck** [comment] 2020-08-12 09:46
@chubzchoc you only get the email and name on the first login with sign in with apple.

You can reset the access [here](https://appleid.apple.com/) for your Apple account and then you would get the email and name again.
