### ISSUE TITLE
Apple login does't work ios version 16.3

### ISSUE THREAD

**Issue by mahmudulhasan766** [aboutyou/dart_packages#361] opened 2023-02-27 10:41 UTC
Apple login work before ios version 16.2 but does't work ios version 16.3

**Comment by HenriBeck** [comment] 2023-02-27 13:09
Could you please provide more information on what exactly fails, what you see in the console and if this happens on a simulator or real device?

**Comment by efraespada** [comment] 2023-03-16 00:48
Same problem here. In my case, Apple reviewers always report a "Sign in not complete" error with iOS 16.3.

IOS 16.2 works as expected.

**Comment by Xyzcancer** [comment] 2023-03-27 10:42
@HenriBeck the same issue here. Not able to pass Apple review team
But on my device it works fine 
They gave me device params for review:
- Device type: iPad 
- OS version: iOS 16.3.1

That is the exception that I'm getting from them

SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.))

**Comment by liri2006** [comment] 2023-04-07 09:52
Same here, Apple reviewer reported that sign in does not work on iOS 16.4.

**Comment by HenriBeck** [comment] 2023-04-08 07:36
There is little we can do here from the plugin side since the error happens in Apple's Domain. 

I can't say why this happens, but for our Apps, this was never reported back from Apple.

@efraespada are you able to get some logs from XCode?

**Comment by flutterWithChris** [comment] 2023-04-22 14:58
I'm having these critical issues as well. Sign up is failing on my app, so users never get to onboard :(. This is bad.

**Comment by leochiu-work** [comment] 2023-04-23 07:48
I am having the same issue. Apple rejected my app with following OS.

Review device details:

- Device type: iPad 
- OS version: iOS 16.4.1


I don't have issue in  iOS 16.0.2

**Comment by flutterWithChris** [comment] 2023-04-29 16:03
> [Update 2] Without uploading new build, I tried to reply Apple and told them I couldn't reproduce the issue. Eventually, Apple said they managed to login successfully.
> 
> [Update 1] I have just updated my iPhone to iOS 16.4.1, and tried to login With Apple again. And I don't have problem.
> 
> I don't even know what is the problem now!
> 
> [Original]
> 
> I am having the same issue. Apple rejected my app with following OS.
> 
> Review device details:
> 
>     * Device type: iPad
> 
>     * OS version: iOS 16.4.1
> 
> 
> I don't have issue in iOS 16.0.2

My build was eventually accepted too. But, I see empty user accounts being created in Firestore. 

I suspect that this only affect first time users / sign ins. Which is why the Apple reviewer eventually gets in because the first sign up doesn't work but then they try again & get in.

However, having the auth work the first time is obviously critical to any app.

So, I'm at a loss for what to do. My app is failing to even work for new users, who probably then delete it.

**Comment by letiagoalves** [comment] 2023-08-13 00:09
I've been trying to reproduce this issue for the last days with no success. Apple Review team constantly reproduces this issue with the following device:
- Device type: iPad 
- OS version: iOS 16.6

App is stuck in review process and I have no idea how to solve this since I am not able to even force the issue to happen on my side.

**Comment by tudosxxx** [comment] 2023-09-20 01:37
I also updated my app and it was rejected by Apple after review. The picture I was given was exactly the same as the one above.
Device type: iPone
OS version: iOS 17

**Comment by tudosxxx** [comment] 2023-12-28 08:27
Today the review failed again for ipad ios17.2. The picture given by Apple keeps spinning around after logging in

**Comment by TeixeiraNelson** [comment] 2024-02-20 09:34
Hi Guys, same here. Got the exact same error. 'Sign-up not completed' when I try to login using the plugin. App got rejected from review but it is the exact same code than previous versions of my app that were working perfectly fine. I think there is an issue with iOS 17. How can I fix it ?

**Comment by philpinola1** [comment] 2024-03-19 20:44
App Review is saying that when they tap the "Login with Apple" button the app is crashing but is not providing crash logs. I tried recreating the crash and could not. They're on iPad Air 5th gen iOS 17.4, I'm on iPad Mini 6th gen iOS 17.4. I'm developing on Windows (relying on Codemagic for iOS builds) and have little insight to the apple/XCode ecosystem. Is there any hope in sight for a fix?

**Comment by AdMeen89** [comment] 2024-10-09 22:21
Any updates?

**Comment by HenriBeck** [comment] 2024-10-10 07:17
We will close this issue because iOS 16.3 is now older than 1.5 years ago, and we haven’t gotten a clear, reproducible example.

Please keep in mind that we only provide a smaller wrapper around Apple's interface. This plugin is unlikely to cause any error shown within the pop-up from Apple.

**Closed by HenriBeck** 2024-10-10 07:17 UTC
